service: facial-reaction-parser

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: # region
  profile: # profile name
  environment:
    DYNAMODB_TABLE: # DynamoDB table name
    S3_BUCKET: # S3 bucket name
    SNS_TOPIC_ARN: # SNS topic ARN
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
      Resource: "${self:provider.environment.SNS_TOPIC_ARN}"

functions:
  parse_face:
    handler: facial-reaction-parser/handler.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
          existing: true
  write_to_dynamodb:
    handler: dynamodb-writer/handler.handler
    events:
      - sns: ${self:provider.environment.SNS_TOPIC_ARN}

resources:
  Resources:
    FacialRatingDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
