service: dynamodb-writer

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: # Specify region used in supporting_scripts/setup.py
  profile: # profile name
  environment:
    DYNAMODB_TABLE: ${ssm:/FacialProductRating/RATING_DYNAMODB_TABLE}
    SNS_TOPIC_ARN: ${ssm:/FacialProductRating/SNS_ARN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - sns:Subscribe
      Resource: "${self:provider.environment.SNS_TOPIC_ARN}"

functions:
  write_to_dynamodb:
    handler: handler.handler
    events:
      - sns: ${self:provider.environment.SNS_TOPIC_ARN}
