service: facial-reaction-parser

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: # Specify region used in supporting_scripts/setup.py
  profile: # profile name
  environment:
    S3_BUCKET:  ${ssm:/FacialProductRating/RATING_S3_BUCKET}
    SNS_TOPIC_ARN: ${ssm:/FacialProductRating/SNS_ARN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "${self:provider.environment.SNS_TOPIC_ARN}"

functions:
  parse_face:
    handler: handler.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
          existing: true
